version: '3.8'
volumes:
  data:

services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpw
      - MYSQL_DATABASE=transactionsdb
    ports:
      - 3306:3306
    volumes:
      - .dbdata:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8081:8080
